services:
- type: web
  name: carl-thomas-electric
  env: Python
  region: otc
  branch: main
  plan: starter-free
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
  repo: mico1117153817/carl-thomas-electric-invoicing
